### PR TITLE
Use node_id in unique_id and mqtt topics

### PR DESCRIPTION
**Pull request by elratt0r**
This patch makes use of the MQTT_NODE_ID and MQTT_DEVICE_NAME values to form unique mqtt topics so there can be multiple devices at the same time.

### CODE REVIEW

**Comment by lanrat** [comment]
Looks Great! Thanks.

**Comment by lanrat** [comment]
I think it was due to one of your prior merged PRs. But I'm noticing that my boot_count, activity_count, and boot_reason stats are no longer being updated in HASS. The values in MQTT seem to be correct.


Are you having this same issue or is it something with my setup?

**Comment by elratt0r** [comment]
I had this problem once when there were a leftover device inside HA. I had to delete it with the three dots next to "MQTT Info", then restart the homeplate and reenable the diagnostic sensors.

**Comment by elratt0r** [comment]
Looks all good. Maybe HA got a hickup in the subscribe? Does the sensor show in the MQTT Info part? Does the data under "Subscribed topics" match "homeassistant/sensor/homeplate/boot/state" and are there any received telegrams?

scr_hass_boot

**Comment by lanrat** [comment]
It does not...

I was thinking since I combine the state of these sensors into a single state, that HA could be buggy with that, but I do the same for battery & voltage which work as expected.

Screen Shot 2022-12-10 at 3 27 06 PM

**Comment by elratt0r** [comment]
Combining works fine usually. It looks like HA somehow swallowed the setup topic for this sensor. Try deleting the device and restart HA. (I see that all the disabled sensors are missing, are they visible in the diagnostics tab, maybe under the hidden version?)

**Comment by lanrat** [comment]
I figured it out! When I deleted and re-added my homeplate to fix the device info now showing up, it reset the sensor states that are disabled by default. After re-enabling them they started working again.

Screen Shot 2022-12-10 at 3 43 31 PM

**Comment by lanrat** [comment]
I thing the "MQTT INFO" button should still show that data for debugging purposes, especially if it can show it with a disabled annotation....

**Pull request merged**
